# Config file for automatic testing at travis-ci.org

language: python
python:
  - "3.4"
  - "3.5"

# install dependencies
install: 
  - pip install -r requirements.txt
  - pip install -e ".[test]"

# run tests
script: 
  - python setup.py test
